### ISSUE TITLE
Compilation fails on Windows

### ISSUE THREAD

**Issue by hepptho** [ynqa/promkit#15]
Thank you for making this library, it looks very nice!

Unfortunately, `fake_input` uses `os::unix`, preventing compilation on Windows.

I don't know if what `fake_input` does is possible in a cross-platform fashion, but since it appears to be a utility for testing, and not essential to the library itself, maybe the module could, for now, be omitted on Windows via `cfg`?

**Comment by ynqa** [comment]
@hepptho Thank you for the report. Since there are no internal dependencies on `fake_input` currently, I will remove it from within promkit.
- https://github.com/ynqa/promkit/pull/14/commits/73355151b504f0e6bd3f345f414174f5eb50b277

**Comment by ynqa** [comment]
@hepptho Thank you for the report!

Since there are no internal dependencies on `fake_input` currently, I will remove it from within promkit.
- https://github.com/ynqa/promkit/pull/14/commits/73355151b504f0e6bd3f345f414174f5eb50b277

**Comment by ynqa** [comment]
In [promkit@dev-0.3.1](https://github.com/ynqa/promkit/tree/dev-0.3.1/main),
although on MacOS, I have confirmed that you can build binaries for Windows following these steps.

```bash
brew install mingw-w64
rustup target add x86_64-pc-windows-gnu
cargo build --target=x86_64-pc-windows-gnu
```

**Comment by hepptho** [comment]
Can confirm dev-0.3.1 compiles on Windows with both gnu and msvc toolchains 👍 
Thank you!

**Comment by ynqa** [comment]
Handled the commit https://github.com/ynqa/promkit/commit/73355151b504f0e6bd3f345f414174f5eb50b277 in #14.
